version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - mysql_storage:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: akashdeep
                        MYSQL_PASSWORD: ak
                        MYSQL_DATABASE: mydb

        wordpressos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - dbos
                ports:
                        - 8090:80
                environment:
                        WORDPRESS_DB_HOST: dbos
                                          WORDPRESS_DB_USER: akashdeep
                        WORDPRESS_DB_PASSWORD: ak
                        WORDPRESS_DB_NAME: mydb
                volumes:
                        - wp_storage:/var/www/html


volumes:
        wp_storage:
        mysql_storage:
